name: MLflow CI Training

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install MLflow
      run: |
        pip install mlflow

    - name: Run MLflow Project
      run: |
        mlflow run MLProject

    - name: Save MLflow artifacts
      run: |
        mkdir artifacts
        cp -r mlruns artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: artifacts/
