name: Training Pipeline

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install mlflow scikit-learn pandas numpy matplotlib joblib openpyxl

    - name: Run MLflow Project
      run: |
        # PERBAIKAN: --no-conda diganti menjadi --env-manager=local
        mlflow run ./MLProject --env-manager=local